import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import AppWrapper from "./AppWrapper";

export const metadata: Metadata = {
    title: "Skin Disease Identifier",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AppWrapper>
                    <Nav />
                    {children}
                </AppWrapper>
            </body>
        </html>
    );
}
